[workspace]
members = [
    "crates/mnn-runtime",
    "crates/mnn-runtime-sys",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["ChenZibo <qw.54@163.com>"]
license = "Apache-2.0"
repository = "https://github.com/zibo-chen/mnn-runtime-rs"
homepage = "https://github.com/zibo-chen/mnn-runtime-rs"

[workspace.dependencies]
thiserror = "2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
